routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
    Route::resource('label', 'LabelController', [
        'only' => ['index', 'show']
    ]);
    Route::resource('instance', 'InstanceController', [
        'only' => ['show']
    ]);
    Route::post('user/favorites/set', 'FavoritesController@setFavorite')->name('favorites.set');
    Route::get('user/favorites', 'FavoritesController@show')->name('favorites.show');

    Route::get('user/profile', 'HomeController@profile')->name('profile');

    Route::get('storage/{folder}/{filename}', function ($folder, $filename)
    {
        $path = storage_path('app/'.$folder.'/'.$filename);

        if (!File::exists($path)) {
            abort(404);
        }

        $file = File::get($path);
        $type = File::mimeType($path);

        $response = Response::make($file, 200);
        $response->header("Content-Type", $type);

        return $response;
    });
});

/*
 * Auth routes. We don't use Auth::routes() as not all routes are desired.
 */
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::match(['get', 'post'], 'logout', 'Auth\LoginController@logout')->name('logout');

Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

app/Instance.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Instance extends Model
{
    public function label()
    {
        return $this->belongsTo('App\Label');
    }

    public function getImagePathAttribute()
    {
        return Storage::url($this->image ?: 'instance_images/no_image_available.jpg');
    }

    public function getCroppedImagePathAttribute()
    {
        return Storage::url($this->image ? 'crop_'.$this->image : 'instance_images/no_image_available.jpg');
    }

    public function getBoundingBoxAttribute()
    {
        return array(
            'x' => $this->top_x,
            'y' => $this->top_y,
            'width' => $this->bottom_x - $this->top_x,
            'height' => $this->bottom_y - $this->top_y,
        );
    }
}

resources/views/favorites.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('home') }}">Dashboard</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Favorites</li>
                    </ol>
                </nav>
                <div class="card">
                    <div class="card-header">Favorites</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif
                        @if(Auth::user()->favorites->isEmpty())
                            <div>You have not added any favorites yet. Press the star icon to add an item to your favorites.</div>
                        @else
                            <div class="card-columns">
                                @foreach(Auth::user()->favorites as $instance)
                                    <div class="card">
                                        <div class="card-header">
                                            {{ $instance->label->label }}
                                        </div>
                                        <img class="card-img-top" src="{{ $instance->cropped_image_path }}" alt="Card image cap">
                                        <div class="card-body">
                                            <a href="{{ route('instance.show', $instance) }}" class="btn btn-primary btn-block">View Location</a>
                                        </div>
                                        <div class="card-footer">
                                            <small class="text-muted">Last seen {{ $instance->updated_at->diffForHumans() }}</small>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        (function (labelshow, $, undefined) {

        }(window.labelshow = window.labelshow || {}, jQuery))

    </script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="card">
                                    <div class="card-body">
                                        <h5 class="card-title">Items</h5>
                                        <p class="card-text">Show a list of items which have been located.</p>
                                        <a href="{{ route('label.index') }}" class="btn btn-primary">Items</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="card">
                                    <div class="card-body">
                                        <h5 class="card-title">Favorites</h5>
                                        <p class="card-text">Show only items that have been added to favorites.</p>
                                        <a href="{{ route('favorites.show') }}" class="btn btn-primary">Favorites</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    (function (home, $, undefined) {

    }(window.home = window.home || {}, jQuery))

</script>
@endsection

resources/views/profile.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Profile</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div id="passport">
                        <passport-clients></passport-clients>
                        <passport-authorized-clients></passport-authorized-clients>
                        <passport-personal-access-tokens></passport-personal-access-tokens>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    (function (home, $, undefined) {

    }(window.home = window.home || {}, jQuery))

</script>
@endsection