routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
    Route::resource('label', 'LabelController', [
        'only' => ['index', 'show']
    ]);
    Route::resource('instance', 'InstanceController', [
        'only' => ['show']
    ]);
    Route::post('user/favorites/set', 'FavoritesController@setFavorite')->name('favorites.set');
    Route::get('user/favorites', 'FavoritesController@show')->name('favorites.show');

    Route::get('user/profile', 'HomeController@profile')->name('profile');

    Route::get('storage/{folder}/{filename}', function ($folder, $filename)
    {
        $path = storage_path('app/'.$folder.'/'.$filename);

        if (!File::exists($path)) {
            abort(404);
        }

        $file = File::get($path);
        $type = File::mimeType($path);

        $response = Response::make($file, 200);
        $response->header("Content-Type", $type);

        return $response;
    });
});

/*
 * Auth routes. We don't use Auth::routes() as not all routes are desired.
 */
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::match(['get', 'post'], 'logout', 'Auth\LoginController@logout')->name('logout');

Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

app/Instance.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Instance extends Model
{
    public function label()
    {
        return $this->belongsTo('App\Label');
    }

    public function getImagePathAttribute()
    {
        return Storage::url($this->image ?: 'instance_images/no_image_available.jpg');
    }

    public function getCroppedImagePathAttribute()
    {
        return Storage::url($this->image ? 'crop_'.$this->image : 'instance_images/no_image_available.jpg');
    }

    public function getBoundingBoxAttribute()
    {
        return array(
            'x' => $this->top_x,
            'y' => $this->top_y,
            'width' => $this->bottom_x - $this->top_x,
            'height' => $this->bottom_y - $this->top_y,
        );
    }
}

app/Http/Controllers/InstanceController.php
<?php

namespace App\Http\Controllers;

use App\Instance;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class InstanceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Instance  $instance
     * @return \Illuminate\Http\Response
     */
    public function show(Instance $instance)
    {
        return view('instance.show', [
            'instance' => $instance,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Instance  $instance
     * @return \Illuminate\Http\Response
     */
    public function edit(Instance $instance)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Instance  $instance
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Instance $instance)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Instance  $instance
     * @return \Illuminate\Http\Response
     */
    public function destroy(Instance $instance)
    {
        //
    }

    public function image(Request $request, Instance $instance)
    {
        if ($request->hasFile('img')) {
            if($request->file('img')->isValid()) {
                try {
                    // Store the image in the private storage folder.
                    $imgPath = $request->img->store('instance_images');
                    $imgCropPath = 'crop_' . $imgPath;

                    // Get the bounding box and crop the image.
                    $rect = $instance->bounding_box;
                    $imgCrop = Image::make($request->img);
                    $width = $imgCrop->width();
                    $height = $imgCrop->height();
                    $imgCrop->crop(intval($width * $rect['width']), intval($height * $rect['height']), intval($width * $rect['x']), intval($height * $rect['y']));

                    // Store the cropped image in the private storage folder.
                    Storage::put($imgCropPath, $imgCrop->encode('png'));

                    // Delete the previous image for this instance.
                    if ($instance->image) {
                        Storage::delete([
                            $instance->image,
                            $instance->crop_image,
                        ]);
                    }

                    $instance->image = $imgPath;
                    $instance->crop_image = $imgCropPath;
                    $instance->save();

                    return response()->json([
                        'success' => true,
                    ]);
                } catch (Exception $e) {
                    return response()->json([
                        'success' => false,
                        'message' => 'Exception: '.$e->getMessage(),
                    ], 500);
                }
            } else {
                return response()->json([
                    'success' => false,
                    'message' => 'Invalid file',
                ], 400);
            }
        } else {
            return response()->json([
                'success' => false,
                'message' => 'No file in request',
            ], 400);
        }
    }
}

resources/views/instance/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('home') }}">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('label.index') }}">Items</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('label.show', $instance->label) }}">{{ $instance->label->label }}</a></li>
                        <li class="breadcrumb-item active" aria-current="page">{{ $instance->label->label . ' ' . $instance->id }}</li>
                    </ol>
                </nav>
                <div class="card">
                    <div class="card-header">{{ $instance->label->label . ' ' . $instance->id }}
                        <i id="favorite" data-feather="star" stroke-width="1.5"
                                {!! Auth::user()->favorites->contains('id', $instance->id) ? 'fill="gold"' : '' !!}
                                data-toggle="tooltip" data-placement="top" title="Toggle favorites">
                        </i></div>

                    <div id="card" class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif
                        <h5 class="text-muted">Last seen {{ $instance->updated_at->diffForHumans() }}</h5>

                        <img id="image" src="{{ $instance->image_path }}" alt="Card image cap" hidden>
                        <canvas id="canvas" width="100%" height="100%"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        (function (instanceshow, $, undefined) {
            feather.replace();
            $('[data-toggle="tooltip"]').tooltip();

            $('#favorite').on('click', function (e) {
                let favorite;

                if ($(this).attr('fill') === 'gold') {
                    $(this).attr('fill', 'none');
                    favorite = false;
                } else {
                    $(this).attr('fill', 'gold');
                    favorite = true;
                }


                $.ajax({
                    url: '{{ route('favorites.set') }}',
                    method: 'POST',
                    data: {
                        _token: "{{ csrf_token() }}",
                        favorite: +favorite,
                        instance_id: '{{ $instance->id }}',
                    },
                });

            });

            window.onload = function () {
                let canvas = document.getElementById('canvas');
                let cardWidth = $('#card').width()
                let ctx = canvas.getContext('2d');
                let img = document.getElementById('image');
                let outerBoundingBox = {!! json_encode($instance->bounding_box) !!}

                if (img.width > cardWidth) {
                    ctx.canvas.width = cardWidth;
                    ctx.canvas.height = img.height * (cardWidth / img.width);
                } else {
                    ctx.canvas.width = img.width;
                    ctx.canvas.height = img.height;
                }

                outerBoundingBox.width *= ctx.canvas.width;
                outerBoundingBox.height *= ctx.canvas.height;
                outerBoundingBox.x *= ctx.canvas.width;
                outerBoundingBox.x += outerBoundingBox.width / 2;
                outerBoundingBox.y *= ctx.canvas.height;
                outerBoundingBox.y += outerBoundingBox.height / 2;
                outerBoundingBox.lineWidth = 4;
                outerBoundingBox.strokeStyle = '#333E4B';
                outerBoundingBox.fillStyle = 'transparent';
                outerBoundingBox.anchor = 'center';

                let innerBoundingBox = _.clone(outerBoundingBox);
                outerBoundingBox.strokeStyle = '#FFFFFF';
                innerBoundingBox.lineWidth = 2;

                let image = new Facade.Image(img, {
                    x: 0,
                    y: 0,
                    width: img.width,
                    height: img.height,
                    scale: img.width > cardWidth ? (cardWidth / img.width) : 1,
                    anchor: 'top/left'
                });

                let outerRect = new Facade.Rect(outerBoundingBox);
                let innerRect = new Facade.Rect(innerBoundingBox);

                let stage = new Facade(document.querySelector('canvas')/*, ctx.canvas.width, ctx.canvas.height*/);
                let scale = 0;

                stage.draw(function () {
                    this.clear();

                    scale += 0.02;

                    if (scale > 1) {
                        scale = 1;
                    }

                    this.addToStage(image);
                    this.addToStage(outerRect, {scale: scale});
                    this.addToStage(innerRect, {scale: scale});
                });
            };
        }(window.instanceshow = window.instanceshow || {}, jQuery))

    </script>
@endsection